"use client";

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, Trash2 } from "lucide-react";

/** One row in a customizer scope (label, slug, optional color, optional is_core). */
export interface CustomizerOptionRow {
  slug: string;
  label: string;
  color?: string | null;
  is_core?: boolean;
}

export interface CustomizerOptionsTableProps {
  /** Scope slug shown in footer (e.g. contact_status, note_type). Fixed in code, not autogenerated. */
  scope: string;
  /** Current items; order = display_order. */
  items: CustomizerOptionRow[];
  /** Called when user edits, reorders, adds, or removes. */
  onItemsChange: (items: CustomizerOptionRow[]) => void;
  /** Called when user clicks Save. */
  onSave: () => void;
  saving: boolean;
  saved: boolean;
  isSuperadmin?: boolean;
  /** Show color picker + hex column. Default true. */
  showColor?: boolean;
  /** Slug that cannot be deleted and has read-only slug field (e.g. "new" for contact status). */
  protectedSlug?: string;
  addButtonLabel?: string;
  saveButtonLabel?: string;
  emptyLabel?: string;
  /** Returns the default row for Add. */
  getDefaultItem: () => CustomizerOptionRow;
  /** Return false to disable Save (e.g. validation). */
  validateForSave?: (items: CustomizerOptionRow[]) => boolean;
}

export function CustomizerOptionsTable({
  scope,
  items,
  onItemsChange,
  onSave,
  saving,
  saved,
  isSuperadmin = false,
  showColor = true,
  protectedSlug,
  addButtonLabel = "Add",
  saveButtonLabel = "Save",
  emptyLabel = "No items defined",
  getDefaultItem,
  validateForSave,
}: CustomizerOptionsTableProps) {
  const handleFieldChange = (index: number, field: keyof CustomizerOptionRow, value: string | boolean) => {
    onItemsChange(
      items.map((item, i) =>
        i === index ? { ...item, [field]: value } : item
      )
    );
  };

  const handleMoveUp = (index: number) => {
    if (index === 0) return;
    const next = [...items];
    [next[index - 1], next[index]] = [next[index], next[index - 1]];
    onItemsChange(next);
  };

  const handleMoveDown = (index: number) => {
    if (index === items.length - 1) return;
    const next = [...items];
    [next[index], next[index + 1]] = [next[index + 1], next[index]];
    onItemsChange(next);
  };

  const handleRemove = (index: number) => {
    const item = items[index];
    if (!item) return;
    if (protectedSlug && item.slug?.trim().toLowerCase() === protectedSlug.toLowerCase()) return;
    if (item.is_core) return;
    onItemsChange(items.filter((_, i) => i !== index));
  };

  const handleAdd = () => {
    onItemsChange([...items, getDefaultItem()]);
  };

  const canSave = validateForSave ? validateForSave(items) : true;

  return (
    <div className="space-y-2">
      {items.length > 0 && (
        <div className="flex flex-wrap items-center gap-2 px-2 text-sm font-medium text-muted-foreground">
          <div className="w-8 shrink-0" aria-hidden />
          <span className="w-32">Label</span>
          <span className="w-28">Slug</span>
          {showColor && <span className="w-[5.5rem]">Color</span>}
          <span className="flex-1 min-w-4" aria-hidden />
          {isSuperadmin && <span className="whitespace-nowrap">Core</span>}
          <span className="w-8 shrink-0" aria-hidden />
        </div>
      )}
      {items.length === 0 ? (
        <p className="text-sm text-muted-foreground">{emptyLabel}</p>
      ) : (
        items.map((item, index) => {
          const isProtected = protectedSlug && item.slug?.trim().toLowerCase() === protectedSlug.toLowerCase();
          const color = item.color ?? "#6b7280";
          return (
            <div
              key={index}
              className="flex flex-wrap items-center gap-2 p-2 border rounded-md bg-muted/30"
            >
              <div className="flex flex-col gap-0.5 shrink-0">
                <button
                  type="button"
                  className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                  onClick={() => handleMoveUp(index)}
                  disabled={index === 0}
                  aria-label="Move up"
                >
                  <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                  </svg>
                </button>
                <button
                  type="button"
                  className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                  onClick={() => handleMoveDown(index)}
                  disabled={index === items.length - 1}
                  aria-label="Move down"
                >
                  <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
              </div>
              <Input
                placeholder="Label"
                value={item.label}
                onChange={(e) => handleFieldChange(index, "label", e.target.value)}
                className="w-32 h-8 text-sm"
              />
              <Input
                placeholder="Slug"
                value={item.slug}
                onChange={(e) => !isProtected && handleFieldChange(index, "slug", e.target.value)}
                className="w-28 h-8 text-sm font-mono"
                readOnly={!!isProtected}
                title={isProtected ? "Protected — cannot change slug" : undefined}
              />
              {showColor && (
                <div className="flex items-center gap-1">
                  <input
                    type="color"
                    value={color}
                    onChange={(e) => handleFieldChange(index, "color", e.target.value)}
                    className="h-8 w-10 cursor-pointer rounded border border-input"
                    title="Pick color"
                  />
                  <Input
                    value={color}
                    onChange={(e) => handleFieldChange(index, "color", e.target.value)}
                    className="h-8 w-20 font-mono text-xs"
                    placeholder="#000000"
                    title="Hex code (copy or paste)"
                  />
                </div>
              )}
              <div className="flex items-center gap-2 ml-auto shrink-0">
                {isSuperadmin && (
                  <label className="flex items-center gap-1.5 text-sm cursor-pointer">
                    <Checkbox
                      checked={!!item.is_core}
                      onCheckedChange={(checked) =>
                        handleFieldChange(index, "is_core", checked === true)
                      }
                      title="System reserved — non-deletable when checked"
                    />
                    <span className="text-muted-foreground whitespace-nowrap">Core</span>
                  </label>
                )}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleRemove(index)}
                  className="h-8 w-8 p-0 shrink-0 text-muted-foreground hover:text-destructive disabled:opacity-40"
                  disabled={!!isProtected || !!item.is_core}
                  title={
                    item.is_core
                      ? "System reserved — cannot remove"
                      : isProtected
                        ? "Protected — cannot remove"
                        : "Remove"
                  }
                >
                  <Trash2 className="h-3 w-3" />
                </Button>
              </div>
            </div>
          );
        })
      )}
      <div className="flex flex-wrap items-center justify-between gap-4 mt-4">
        <div className="flex items-center gap-2">
          <Button onClick={handleAdd} variant="outline" size="sm">
            <Plus className="h-4 w-4 mr-1" />
            {addButtonLabel}
          </Button>
          <Button onClick={onSave} disabled={saving || !canSave}>
            {saving ? "Saving…" : saveButtonLabel}
          </Button>
          {saved && <span className="text-sm text-green-600">Saved!</span>}
        </div>
        <p
          className="text-xs text-muted-foreground font-mono"
          title="Fixed identifier in code and database; not autogenerated"
        >
          Scope: {scope}
        </p>
      </div>
    </div>
  );
}
